### ISSUE TITLE
Create Clients Profile

### ISSUE THREAD

**Issue by agustinb4** [entropy-code/entropay-employees#4]
As an Entropay admin user I want to create Clients profile SO THAT I can use them for invoicing

Figma reference: https://www.figma.com/file/SYS1w4h4h75LEtnOz1AeZN/Entropay-messy-place?node-id=0%3A1

For form fields consider Active, Inactive, error state
For Save button consider enable, disable status

**ACCEPTANCE CRITERIA**

GIVEN I am an admin user
WHEN enter to Entropay
THEN I see an option to create Clients

GIVEN I am an admin user in Entropay
WHEN click on New Client
THEN I see form with :  Client Name*, Address*, Contact ( Name, lastname and email) and Preferred currency 

GIVEN I am an admin user in Entropay
WHEN fill the New Client form 
THEN I am able to save it

GIVEN I am an admin user in Entropay
WHEN Not fill the requiere fields in New Client form 
THEN save button is not enable

GIVEN I am an admin user in Entropay
AND I am in New client form
WHEN click on Cancel
THEN I close the form 

GIVEN I am an admin user in Entropay
AND I filled Client form
WHEN click on save and is not able to save
THEN I see an error message

Table:
 clients:
- id
- name
- address
- city
- state
- zip
- created_on
- modified_on

**Comment by arael82** [comment]
BE PR https://github.com/entropy-code/entropay-employees/pull/6
